version: '3.8'

services:
  app:
    environment:
      - DOMAIN=your-domain.com
      - PROTOCOL=https
      - BASE_URL=https://your-domain.com
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

secrets:
  db_password:
    file: ./secrets/db_password.txt
