version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DOMAIN=localhost
      - PROTOCOL=http
      - BASE_URL=http://localhost:8080
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=url_shortener
    depends_on:
      - db
    networks:
      - url-shortener-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  url-shortener-network:
    driver: bridge
